version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    # ports:
    #   - '8080:80'
      # - "80:80"
      # - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend-react-app
    networks:
      - dealers-n-deals-network

  frontend-react-app:
    # image: koitoror/node-app-practice
    build:
      context: ./frontend/
      # context: .
      # args:
      #   NODE_ENV: development
    # entrypoint: ['npm', 'run', 'start']
    # command: npm run start
    # env_file: ./frontend/config/config.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
      - /frontend/node_modules:/app/node_modules
      # - ./:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      # - MONGO_USER=koitoror
      # - MONGO_PASSWORD=mypassword
      # - SESSION_SECRET=secret

    depends_on:
      - backend-node-app
    networks:
      - dealers-n-deals-network

  backend-node-app:
    build: .
    environment:
      - PORT=5000
    env_file:
      - ./.env
    volumes:
      - ./:/app
      # - ./:/
      - /node_modules:/app/node_modules
      # - /node_modules:/node_modules
    depends_on:
      - mongo
      # - redis
    networks:
      - dealers-n-deals-network

  mongo:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=koitoror
    #   - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
    restart: always
    networks:
      - dealers-n-deals-network

  # redis:
  #   image: redis

volumes:
  mongo-db:
  # frontend/node_modules:
  node_modules:

networks:
  dealers-n-deals-network:
    driver: bridge
